CREATE TABLE task
(
   id INT NOT NULL AUTO_INCREMENT,
   taskType VARCHAR (100) NOT NULL,
   dueDate VARCHAR (100) NOT NULL,
   taskName VARCHAR (100) NOT NULL,
   comment VARCHAR (500) NOT NULL,
   PRIMARY KEY (id)
);